http://localhost:9999/.netlify/functions/profiles-read-all

####

 https://pwa-profiles.netlify.app/.netlify/functions/profiles-read-all

####

POST http://localhost:9999/.netlify/functions/profiles-create HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
####

POST https://pwa-profiles.netlify.app/.netlify/functions/profiles-create HTTP/1.1
content-type: application/json

{
    
    "name": "ddsfsdfsdf",
    "time": "Wed, 22 Oct 2015 18:27:50 GMT"
}

###

GET https://pwa-profiles.netlify.app/.netlify/functions/profiles-read-all HTTP/1.1

###

